In [2]:
import torch

In [4]:
x = torch.arange(12)

In [5]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.size()

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [12]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])

In [13]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [14]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [15]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [16]:
x%y

tensor([1., 0., 0., 0.])

In [17]:
x**y

tensor([ 1.,  4., 16., 64.])

In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
x = torch.arange(12,dtype = torch.float32).reshape(3,4)
y = torch.tensor([[1,2,3,4],[4,3,2,1],[5,6,4,3]])
torch.cat((x,y),dim = 0), torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.],
         [ 5.,  6.,  4.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  4.,  3.,  2.,  1.],
         [ 8.,  9., 10., 11.,  5.,  6.,  4.,  3.]]))

In [21]:
y == x

tensor([[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])

In [22]:
x.sum()

tensor(66.)

In [23]:
y.tensor()

AttributeError: 'Tensor' object has no attribute 'tensor'

In [24]:
y.sum()

tensor(38)

In [26]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [27]:
a+b # 广播机制

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
x[-1],x

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [30]:
x[1]

tensor([4., 5., 6., 7.])

In [31]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
x[1,2],x

(tensor(6.),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [34]:
x[0:3,3]

tensor([ 3.,  7., 11.])

In [35]:
x[:,3]

tensor([ 3.,  7., 11.])

In [37]:
x[0:2,0:2]

tensor([[0., 1.],
        [4., 5.]])

In [38]:
id(x)

2826916856592

In [39]:
x = x+y

In [40]:
id(x)

2826916856512

In [41]:
x += y

In [42]:
id(x)

2826916856512

In [43]:
z = torch.zeros_like(y)

In [44]:
z

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [48]:
id(z)

2826916929600

In [49]:
z = x+y

In [50]:
id(z)

2826916931360

In [51]:
z = torch.zeros_like(y)
z

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [52]:
id(z)

2826916932800

In [53]:
z = x+y
z

tensor([[ 3.,  7., 11., 15.],
        [16., 14., 12., 10.],
        [23., 27., 22., 20.]])

In [54]:
id(z)

2826916958352

In [55]:
id(z[:])
id(z)

2826916958352

In [56]:
id(z)

2826916958352

In [57]:
id(z[:])

2826916961872

In [58]:
z[:]

tensor([[ 3.,  7., 11., 15.],
        [16., 14., 12., 10.],
        [23., 27., 22., 20.]])

In [59]:
z

tensor([[ 3.,  7., 11., 15.],
        [16., 14., 12., 10.],
        [23., 27., 22., 20.]])

In [60]:
id(z)

2826916958352

In [61]:
z[:] = x+y

In [62]:
id(z)

2826916958352

In [63]:
z

tensor([[ 3.,  7., 11., 15.],
        [16., 14., 12., 10.],
        [23., 27., 22., 20.]])

In [64]:
a = x.numpy()

In [65]:
a

array([[ 2.,  5.,  8., 11.],
       [12., 11., 10.,  9.],
       [18., 21., 18., 17.]], dtype=float32)

In [66]:
type(a)

numpy.ndarray

In [67]:
 import os

In [68]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write("numrooms,alley,price\n")
    f.write('na,pave,12750\n')
    f.write('2,na,10600\n')
    f.write('4,na,17810\n')
    f.write('na,na,14000\n')

# 测试一
h 查看所有快捷键
enter esc
shift+enter 运行当前代码块并且跳到下一个代码块
ctrl+enter 只运行当前代码块
alt + enter 运行代码块并且新建一个代码块
m 变为markdown单元格
y 变为代码单元格
b 在下方新建单元格
a 在上方新建一个代码块
d 删除当前代码块
x 剪切
c 复制
v 粘贴到当前
l 为代码标记行数
shift+v粘贴到上方
latex能够添加数学公式