In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True) # 指示存储x的梯度,避免以后访问的时候重复求导
x.grad

In [4]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4*x

tensor([True, True, True, True])

In [11]:
x.grad.zero_() # 清除默认累计的梯度
x.grad

tensor([0., 0., 0., 0.])

In [12]:
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [17]:
x.grad.zero_()
y = x*x
y,x

(tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor([0., 1., 2., 3.], requires_grad=True))

In [18]:
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [21]:
x.grad.zero_()
y = x*x
u = y.detach() # 建立u 令u与y无关

z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [22]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])