# 数组类型

In [2]:
import numpy as np

In [3]:
#类型转换
a=np.array([1,5,-3],dtype=float)
a

array([ 1.,  5., -3.])

In [7]:
#asarray函数
a=np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [8]:
#astype
a=np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

In [9]:
a  #astype可以返回新的数组，可以对float进行改变而不改变a数组的值

array([1, 2, 3])

# 数组操作

In [11]:
mv_name=['肖申克的救赎','控方证人','美丽人生','阿甘正传','霸王别姬','泰坦尼克号','辛德勒的名单','这个杀手不太冷','疯狂动物城','海豚湾']

In [12]:
mv_num=np.array([692795,42995,327855,580897,478523,157074,306904,662552,284652,159302])

In [13]:
mv_score=np.array([9.6,9.5,9.5,9.4,9.4,9.4,9.4,9.3,9.3,9.3])

In [14]:
mv_length=np.array([142,116,116,142,171,194,195,133,109,92])

数组排序

In [15]:
#sort函数
np.sort(mv_num)    #未改变原有数组

array([ 42995, 157074, 159302, 284652, 306904, 327855, 478523, 580897,
       662552, 692795])

In [16]:
mv_num

array([692795,  42995, 327855, 580897, 478523, 157074, 306904, 662552,
       284652, 159302])

In [22]:
#argsort函数，，返回从小到大的排列数组中的索引位置
order=np.argsort(mv_num)
order

array([1, 5, 9, 8, 6, 2, 4, 3, 7, 0], dtype=int64)

In [23]:
mv_name[order[0]]   #找到观影人数最少的电影的名字

'控方证人'

In [24]:
mv_name[order[-1]]   #找到观影人数最多的电影的名字

'肖申克的救赎'

求和

In [26]:
#评分人数求和
np.sum(mv_num)

3693549

In [28]:
mv_num.sum()

3693549

最大值

In [29]:
#时长最长
np.max(mv_length)

195

In [30]:
mv_length.max()

195

最小值

In [31]:
#时长最短
np.min(mv_length)

92

In [32]:
mv_length.min()

92

均值

In [36]:
np.mean(mv_score)

9.41

In [37]:
mv_score.mean()

9.41

标准差

In [39]:
np.std(mv_score)

0.09433981132056571

In [40]:
mv_score.std()

0.09433981132056571

相关系数矩阵

In [41]:
np.cov(mv_score,mv_length)     #电影评分和电影时长的关系

array([[9.88888889e-03, 4.55555556e-01],
       [4.55555556e-01, 1.26288889e+03]])

# 多维数组操作

数组形状,shape和reshape，reshape不会修改原有的数组，而会返回一个新的数组

shape

In [44]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [47]:
a.shape=2,3
a                #转为2维3列

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a.shape

(2, 3)

reshape

In [49]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [54]:
a.reshape(2,3)           #转为2维3列

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
a

array([0, 1, 2, 3, 4, 5])

转置

In [57]:
a=a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
a.T    #三维二列

array([[0, 3],
       [1, 4],
       [2, 5]])

In [59]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [60]:
a

array([[0, 1, 2],
       [3, 4, 5]])

数组连接

In [64]:
x=np.array([[0,1,2],[10,11,12]])
y=np.array([[90,91,92],[100,101,102]])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [66]:
z=np.concatenate((x,y),axis=0)  #按照列
z

array([[  0,   1,   2],
       [ 10,  11,  12],
       [ 90,  91,  92],
       [100, 101, 102]])

In [67]:
m=np.concatenate((x,y),axis=1)  #按照列
m

array([[  0,   1,   2,  90,  91,  92],
       [ 10,  11,  12, 100, 101, 102]])

In [69]:
z=np.array((x,y))
z

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[ 90,  91,  92],
        [100, 101, 102]]])

numpy中的内置函数关于拼接

In [71]:
#vstack
np.vstack((x,y))

array([[  0,   1,   2],
       [ 10,  11,  12],
       [ 90,  91,  92],
       [100, 101, 102]])

In [72]:
#hstack
np.hstack((x,y))

array([[  0,   1,   2,  90,  91,  92],
       [ 10,  11,  12, 100, 101, 102]])

In [73]:
#dstack
np.dstack((x,y))

array([[[  0,  90],
        [  1,  91],
        [  2,  92]],

       [[ 10, 100],
        [ 11, 101],
        [ 12, 102]]])

numpy内置函数

In [74]:
a=np.array([-1,0,-10,5,7])
a

array([ -1,   0, -10,   5,   7])

In [75]:
np.abs(a)

array([ 1,  0, 10,  5,  7])

In [76]:
np.median(a)

0.0

In [77]:
np.exp(a)

array([3.67879441e-01, 1.00000000e+00, 4.53999298e-05, 1.48413159e+02,
       1.09663316e+03])