In [1]:
import numpy as np

In [2]:
a=[1,2,3,4]
[x+1 for x in a]

[2, 3, 4, 5]

In [3]:
b=[3,4,5,6]
[x+y for (x,y) in zip(a,b)]

[4, 6, 8, 10]

In [5]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a+1

array([2, 3, 4, 5])

In [8]:
b=np.array([3,4,5,6])
a+b

array([ 4,  6,  8, 10])

#  产生数组

从列表中产生

In [12]:
list=[1,2,3,4]
a=np.array(list)
a

array([1, 2, 3, 4])

从列表传入

In [13]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

生成全零数组

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

生成全1数组

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones(5,dtype='bool')

array([ True,  True,  True,  True,  True])

fill方法

In [18]:
a.fill(5)
a

array([5, 5, 5, 5])

参数类型转换

In [20]:
a=a.astype('float')
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

生成整数序列

In [24]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

生成等差数列

In [31]:
a=np.linspace(1,12,20)
a

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

生成随机数

In [32]:
np.random.rand(100)

array([0.48426716, 0.0520742 , 0.12801302, 0.1298599 , 0.14056595,
       0.27444284, 0.71020466, 0.93614431, 0.60549566, 0.57740573,
       0.23059196, 0.42454192, 0.07130194, 0.08186065, 0.01969145,
       0.09471901, 0.5324083 , 0.96967406, 0.51010258, 0.77769849,
       0.19491755, 0.47396615, 0.37356364, 0.87226857, 0.62138563,
       0.39532377, 0.44668339, 0.76195024, 0.69706119, 0.39519284,
       0.49686688, 0.37742223, 0.41430166, 0.77002799, 0.01603968,
       0.31860438, 0.37487348, 0.9472385 , 0.21542437, 0.78763553,
       0.57244449, 0.13304175, 0.32423974, 0.06065059, 0.92335905,
       0.41494479, 0.01042678, 0.87540278, 0.8593319 , 0.65133939,
       0.11492006, 0.54936811, 0.72743363, 0.12765821, 0.39591608,
       0.36262594, 0.49544499, 0.51165584, 0.97170839, 0.83941996,
       0.68019997, 0.20189937, 0.22614106, 0.23482966, 0.36198739,
       0.47207159, 0.20201368, 0.24216956, 0.55967437, 0.49052538,
       0.69496892, 0.55962575, 0.6740713 , 0.91223243, 0.75518

In [34]:
np.random.randn(10)    #服从标准正态分布

array([-0.10508525,  1.78596521,  0.38365017,  1.09283437,  0.03127827,
       -1.32851989, -0.3137156 ,  0.32598103,  0.55833332, -1.901741  ])

In [37]:
np.random.randint(1,100,10)     #生成随机整数

array([87, 93, 21, 59, 44, 21, 92,  6, 11, 69])

# 数组属性

In [38]:
a

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

In [39]:
type(a)

numpy.ndarray

查看数组中的类型

In [42]:
a.dtype

dtype('float64')

查看形状，会返回一个元组，每个元素代表这一堆的元素数目

In [43]:
a.shape

(20,)

In [44]:
a.size  #查看元素的数目

20

In [45]:
a.ndim  #查看维度

1

# 索引和切片

In [46]:
a=np.array([0,1,2,3])
a[0] #索引

0

In [48]:
a[0]=10  #修改第一个
a

array([10,  1,  2,  3])

In [49]:
a=np.array([11,12,13,14,15])
a[1:3]  #取索引号1-3的数，左闭右开

array([12, 13])

In [50]:
a[1:-2]  #负索引，正数第一个到倒数第二个

array([12, 13])

In [51]:
a[-4:3]  #倒数第四个到正数第三个

array([12, 13])

In [52]:
a[-2:] #倒数第二个开始取

array([14, 15])

In [53]:
a[::2]  #间隔为2，取所有

array([11, 13, 15])

# #计算

In [54]:
ob=np.array([21000,21800,22100,23450])
ob

array([21000, 21800, 22100, 23450])

In [58]:
#计算每一天的票房
ob2=ob[1:]-ob[:-1]
ob2

array([ 800,  300, 1350])

# 多维数组及其属性

In [62]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [63]:
a.shape #查看形状

(2, 4)

In [64]:
a.size

8

In [65]:
a.ndim  #查看维度

2

多维数组索引

In [66]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [67]:
a[1,3]  #a[行，列]

13

In [69]:
a[0,1]=15 #更改
a

array([[ 0, 15,  2,  3],
       [10, 11, 12, 13]])

In [70]:
a[0,] #索引第一行

array([ 0, 15,  2,  3])

In [72]:
a[:,3] #索引列，注意前面有冒号

array([ 3, 13])

多维数组切片

In [73]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [74]:
a[0,3:5] #第一行第四个和第五个元素

array([3, 4])

In [75]:
#最后两行的最后两列
a[3:,4:]

array([[34, 35],
       [44, 45]])

In [76]:
#得到第三列
a[:,2]

array([ 2, 12, 22, 32, 42])

In [78]:
#取出第三行和第五行奇数列
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

# 切片在numpy数组中是引用

In [79]:
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [83]:
b=a[0:2]
b

array([0, 1])

In [84]:
b[0]=10
a        #a的值相应也改变

array([10,  1,  2,  3,  4])

# 一些花式索引

In [5]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
index=[1,2,-3]
y=a[index]
print(y)

[10 20 70]


布尔数组进行索引

In [3]:
import numpy as np
mask=np.array([0,2,2,3,0,1,2,0,1,1],dtype=bool)
mask                                             #mask必须是布尔数组，长度必须和数组长度相同

array([False,  True,  True,  True, False,  True,  True, False,  True,
        True])

In [6]:
a[mask]         #在mask定义的位置上为true的，索引。位置：1，2，3，5，6，8，9

array([10, 20, 30, 50, 60, 80, 90])

# 二维花式索引

In [9]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [10]:
#对角线要1，12，23，34，45
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [12]:
#返回最后三行的1，3，5，列      
a[3:,[0,2,4]]

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [14]:
# mask
mask=np.array([1,0,1,0,0,1],dtype=bool)
a[mask,2]   #第三列第一个，第三个，第六个

array([ 2, 22, 52])

# 不完全索引

In [16]:
y=a[:3]
y             #前三行

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [17]:
#取2，3，5，行
con=np.array([0,1,1,0,1,0],dtype=bool)
a[con]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

# where语句

In [19]:
a=np.array([0,12,5,20])
a

array([ 0, 12,  5, 20])

In [18]:
a>10

array([False,  True, False,  True])

In [20]:
np.where(a>10)

(array([1, 3], dtype=int64),)

In [21]:
a[a>10]

array([12, 20])

In [22]:
a[np.where(a>10)]

array([12, 20])