In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [4]:
a = np.arange(20).reshape(4,5)
a,a.T

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]]))

In [5]:
a = np.random.randint(1,10,27)
a.reshape(3,3,3)

array([[[5, 9, 5],
        [1, 7, 3],
        [3, 8, 7]],

       [[4, 8, 6],
        [4, 9, 8],
        [6, 9, 8]],

       [[7, 8, 1],
        [4, 5, 2],
        [8, 9, 5]]])

In [6]:
b = np.random.random((3,3,3))
b

array([[[0.2810624 , 0.20158135, 0.52416608],
        [0.99280309, 0.57903969, 0.49062831],
        [0.37463721, 0.96443917, 0.17062791]],

       [[0.67655512, 0.35208746, 0.80392524],
        [0.51290809, 0.32509345, 0.79305501],
        [0.94168606, 0.92485989, 0.34427037]],

       [[0.05851996, 0.06395958, 0.46955611],
        [0.34433808, 0.77054352, 0.92996343],
        [0.80438153, 0.2383884 , 0.54789651]]])

In [7]:
a = np.random.randint(1,10,10)
a.sort()
a

array([1, 2, 2, 3, 4, 4, 5, 5, 5, 8])

In [8]:
a.max(),a.min(),a.sum(),a.var()

(8, 1, 39, 3.69)

In [9]:
a = np.random.randint(1,10,10)


In [10]:
a = np.linspace(0,100,21,dtype=int)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [11]:
a = np.random.randint(1,11,10)
for i in range(len(a)):
    if a[i]>3 and a[i]<8:
        a[i] = -a[i]

a

array([ 9, -5,  8,  3, -5,  2, -4, 10, 10, -5])

In [12]:
a = np.random.randint(1,11,10)
a[np.where((a>3) & (a<8))]

array([6, 5, 4, 7])

In [14]:
a = np.array([1,2,3,4,5])
b = np.zeros(9,dtype=int)
b[::2] = a
b # 牛逼

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

In [38]:
a = np.random.randint(1,10,25).reshape(5,5)
a


array([[1, 3, 7, 1, 2],
       [9, 6, 9, 3, 1],
       [6, 4, 5, 1, 8],
       [4, 3, 9, 3, 1],
       [5, 7, 3, 5, 4]])

In [39]:
b = a[0].copy() # 交换
a[0] = a[1]
a[1] = b
a

array([[9, 6, 9, 3, 1],
       [1, 3, 7, 1, 2],
       [6, 4, 5, 1, 8],
       [4, 3, 9, 3, 1],
       [5, 7, 3, 5, 4]])

In [40]:
a = np.random.randint(1,10,20).reshape(10,2)
a

array([[2, 6],
       [7, 5],
       [8, 1],
       [6, 3],
       [5, 8],
       [9, 8],
       [5, 1],
       [8, 4],
       [2, 8],
       [2, 2]])

In [44]:
import math
b = []
for x,y in a:
    l =round( math.sqrt(x**2+y**2),2)
    theta = round(math.atan(y/x),2)
    b.append([l,theta])
b

[[6.32, 1.25],
 [8.6, 0.62],
 [8.06, 0.12],
 [6.71, 0.46],
 [9.43, 1.01],
 [12.04, 0.73],
 [5.1, 0.2],
 [8.94, 0.46],
 [8.25, 1.33],
 [2.83, 0.79]]

In [48]:
a = np.ones(10,dtype=int)
a += 1
a[4] = 1
a

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

In [72]:
a = np.random.randint(1,10,10)

In [73]:
a[a%2==1] = -1
a

array([-1,  4, -1,  4, -1, -1, -1,  8, -1, -1])

In [77]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [82]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [88]:
np.random.random((3,4)).round(2)*10

array([[3.4, 7.6, 3.8, 2.2],
       [8. , 0.2, 2.1, 8.9],
       [1.5, 7.2, 7.7, 8.8]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
np.empty((3,4))

198 ns ± 1.76 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [96]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y

array([ 0., 10., 20., 30., 40.])

In [97]:
y = np.zeros(10)
np.power(2,x,y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [100]:
np.add.reduce(x)

10

In [101]:
x = np.random.random((10,3))
x

array([[0.06995309, 0.75089555, 0.77134313],
       [0.79533691, 0.47333521, 0.18237113],
       [0.72327079, 0.00175106, 0.17854885],
       [0.36872487, 0.81020878, 0.04287999],
       [0.56043768, 0.0101551 , 0.3234185 ],
       [0.31938265, 0.41675893, 0.02568758],
       [0.30675869, 0.60688895, 0.18948999],
       [0.5478948 , 0.50729626, 0.98570567],
       [0.32781248, 0.9510205 , 0.27872399],
       [0.47679938, 0.74118326, 0.69770165]])

In [103]:
x.mean(axis=0)

array([0.44963713, 0.52694936, 0.36758705])

In [108]:
x = x-x.mean(axis=0)

In [110]:
x.mean(0)

array([-8.88178420e-17, -3.33066907e-17,  3.33066907e-17])

In [113]:
x = np.linspace(0,5,50)
y = np.linspace(0,5,50)[:,np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

In [115]:
rand = np.random.RandomState(10)
x = rand.randint(100,size=10)
x

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])