In [1]:
import numpy as np

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [6]:
a = np.arange(20).reshape(4,5)
a,a.T

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]]))

In [15]:
a = np.random.randint(1,10,27)
a.reshape(3,3,3)

array([[[7, 7, 1],
        [4, 6, 3],
        [4, 8, 7]],

       [[8, 7, 6],
        [7, 1, 8],
        [7, 5, 8]],

       [[7, 9, 3],
        [6, 7, 5],
        [8, 9, 2]]])

In [18]:
b = np.random.random((3,3,3))
b

array([[[0.01932222, 0.83833695, 0.44807928],
        [0.88588517, 0.75497638, 0.7097662 ],
        [0.53045623, 0.37364303, 0.96020408]],

       [[0.12494312, 0.42230987, 0.68278921],
        [0.69019007, 0.13892612, 0.15659693],
        [0.30673381, 0.43865863, 0.27852933]],

       [[0.52723052, 0.88873728, 0.75326699],
        [0.82324069, 0.410824  , 0.31876345],
        [0.1419195 , 0.91778418, 0.14527986]]])

In [21]:
a = np.random.randint(1,10,10)
a.sort()
a

array([1, 1, 4, 4, 5, 8, 8, 9, 9, 9])

In [23]:
a.max(),a.min(),a.sum(),a.var()

(9, 1, 58, 9.360000000000003)

In [24]:
a = np.random.randint(1,10,10)


In [29]:
a = np.linspace(0,100,21,dtype=int)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [33]:
a = np.random.randint(1,11,10)
for i in range(len(a)):
    if a[i]>3 and a[i]<8:
        a[i] = -a[i]

a

array([ 9, -7, 10, -6,  2,  8, 10,  2,  9,  3])

In [45]:
a = np.random.randint(1,11,10)
a[np.where((a>3) & (a<8))]*-1
a

array([6, 8, 1, 3, 5, 6, 1, 5, 5, 7])