In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [17]:
a+1,a*2

(array([2, 3, 4, 5]), array([2, 4, 6, 8]))

In [18]:
b = np.array([2,3,4,5])
a+b

array([3, 5, 7, 9])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones(40).reshape(4,5,2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
np.ones(5,dtype="str")

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [25]:
a = np.array([1,2,3,4])
a.fill(5) # 每个元素都等于5

In [26]:
a

array([5, 5, 5, 5])

In [27]:
a = a.astype("float")
a

array([5., 5., 5., 5.])

In [29]:
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a = np.linspace(1,10,19)
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [35]:
np.random.rand(10)

array([0.6453292 , 0.05774745, 0.82840387, 0.89805217, 0.94907223,
       0.80484071, 0.66316898, 0.51135512, 0.6120159 , 0.27587657])

In [36]:
np.random.randn(10)

array([ 0.54313284,  0.43227527,  0.36108135,  0.20404642, -0.00335217,
        0.4774457 ,  0.31391217,  0.17528109,  0.75283831,  0.98660968])

In [38]:
np.random.randint(1,10,100)

array([7, 9, 8, 7, 6, 9, 1, 6, 2, 3, 4, 3, 7, 5, 1, 7, 8, 5, 1, 9, 3, 4,
       5, 7, 5, 4, 5, 3, 2, 1, 5, 3, 8, 5, 1, 2, 3, 5, 4, 8, 3, 7, 9, 7,
       6, 1, 6, 1, 2, 1, 5, 9, 4, 2, 7, 2, 9, 7, 7, 3, 1, 6, 2, 5, 7, 7,
       8, 4, 8, 5, 2, 9, 6, 3, 2, 5, 4, 1, 1, 6, 5, 7, 8, 5, 3, 9, 2, 8,
       1, 7, 5, 6, 1, 1, 4, 5, 1, 1, 1, 4])

In [39]:
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.dtype

dtype('float64')

In [42]:
a.shape

(19,)

In [44]:
a.size

19

In [45]:
a.ndim

1

In [46]:
a = np.array([0,1,2,3])
a[0]

0

In [48]:
a[0] = 99
a

array([99,  1,  2,  3])

In [49]:
a = np.arange(11,16)
a

array([11, 12, 13, 14, 15])

In [50]:
a[1:3]

array([12, 13])

In [51]:
a[1:-2]

array([12, 13])

In [52]:
a[-4:3]

array([12, 13])

In [53]:
ob = np.array([2,4,6,8,10])
ob2 = ob[1:]
ob3 = ob[:-1]
ob2,ob3

(array([ 4,  6,  8, 10]), array([2, 4, 6, 8]))

In [54]:
ob2 - ob3

array([2, 2, 2, 2])

In [57]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [58]:
a.ndim

2

In [59]:
a[1,3]

13

In [60]:
a[1]

array([10, 11, 12, 13])

In [62]:
a[:,1]

array([ 1, 11])

In [64]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [68]:
a[-2:,-2:]

array([[22, 23],
       [28, 29]])

In [73]:
a[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [74]:
a = np.array([1,2,3,4,5])
b = a[2:4].copy()
b[1] = 99
a

array([1, 2, 3, 4, 5])

In [75]:

a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [77]:
index = [1,2,-3]
y = a[index] # 花式索引
y

array([10, 20, 70])

In [78]:
mask = np.array([0,2,2,0,0,1,0,0,1,0],dtype="bool")
mask

array([False,  True,  True, False, False,  True, False, False,  True,
       False])

In [79]:
a[mask]

array([10, 20, 50, 80])

In [82]:
a = np.arange(36).reshape(6,6)

In [83]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [84]:
a = np.array([0,12,5,20])
a>10

array([False,  True, False,  True])

In [85]:
np.where(a>10)

(array([1, 3], dtype=int64),)

In [86]:
a[np.where(a>10)]

array([12, 20])

In [87]:
a = np.array([1,2.5],dtype=float)

In [88]:
a

array([1. , 2.5])

In [90]:
a = np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [92]:
a = np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

In [93]:
mv_name=['肖申克的救赎','控方证人','美丽人生','阿甘正传','霸王别姬','泰坦尼克号','辛德勒的名单','这个杀手不太冷','疯狂动物城','海豚湾']
mv_num=np.array([692795,42995,327855,580897,478523,157074,306904,662552,284652,159302])
mv_score=np.array([9.6,9.5,9.5,9.4,9.4,9.4,9.4,9.3,9.3,9.3])
mv_length=np.array([142,116,116,142,171,194,195,133,109,92])

In [94]:
np.sort(mv_num)

array([ 42995, 157074, 159302, 284652, 306904, 327855, 478523, 580897,
       662552, 692795])

In [100]:
order  = np.argsort(mv_num)
order

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [102]:
mv_name[order[-1]]

'海豚湾'

In [103]:
np.sum(mv_num)

3693549

In [104]:
mv_num.sum()

3693549

In [105]:
np.max(mv_length)

195

In [106]:
mv_length.max()

195

In [107]:
np.std(mv_length)

33.713498780162226

In [108]:
mv_length.std()

33.713498780162226

In [109]:
np.cov(mv_score,mv_length)

array([[9.88888889e-03, 4.55555556e-01],
       [4.55555556e-01, 1.26288889e+03]])

In [110]:
a = np.arange(6)

In [111]:
a.shape = 2,3

In [112]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [114]:
a.transpose() #转置

array([[0, 3],
       [1, 4],
       [2, 5]])

In [115]:
a.T.T

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
x = np.array([[0,1,2],[10,11,12]])
y = np.array([[50,51,52],[60,61,62]])
x,y

(array([[ 0,  1,  2],
        [10, 11, 12]]),
 array([[50, 51, 52],
        [60, 61, 62]]))

In [119]:
z = np.concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [121]:
z = np.array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [122]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [123]:
np.hstack((x,y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [124]:
np.dstack((x,y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

In [125]:
np.median(a)

2.5

In [126]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)